sudo : required
services : 
 -docker
before_install :
 - docker build -t viswa2489/client -f Dockerfile.dev  .
script:
 - docker run -e CI=true viswa2489/client npm run test 
deploy :
 provider : elasticbeanstalk
 region :"us-east-1"
 app : "client"
 env : "Client-env"
 bucket_name: "elasticbeanstalk-us-east-1-377807663255"
 bucket_path: "client"
 on :
  branch: master
 access_key_id:
  secure: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_PASSWORD"
